content = open('engine/desktop_control.py', encoding='utf-8').read()

replacements = [
    ('speak("Window minimized")', 'speak("Window minimize kar diya Sir")'),
    ('speak("Window maximized")', 'speak("Window maximize kar diya Sir")'),
    ('speak("Window closed")', 'speak("Window band kar diya Sir")'),
    ('speak("Switching window")', 'speak("Window switch kar raha hoon Sir")'),
    ('speak("Showing desktop")', 'speak("Desktop show kar diya Sir")'),
    ('speak("Snapped to left")', 'speak("Left side snap kar diya Sir")'),
    ('speak("Snapped to right")', 'speak("Right side snap kar diya Sir")'),
    ('speak("Opening task view")', 'speak("Task view khol diya Sir")'),
    ('speak("Copied")', 'speak("Copy kar diya Sir")'),
    ('speak("Pasted")', 'speak("Paste kar diya Sir")'),
    ('speak("Cut")', 'speak("Cut kar diya Sir")'),
    ('speak("Undo done")', 'speak("Undo kar diya Sir")'),
    ('speak("Redo done")', 'speak("Redo kar diya Sir")'),
    ('speak("Selected all")', 'speak("Sab select kar diya Sir")'),
    ('speak("Saved")', 'speak("Save kar diya Sir")'),
    ('speak("New tab opened")', 'speak("Naya tab khol diya Sir")'),
    ('speak("Tab closed")', 'speak("Tab band kar diya Sir")'),
    ('speak("Refreshed")', 'speak("Refresh kar diya Sir")'),
    ('speak("Going back")', 'speak("Peeche ja raha hoon Sir")'),
    ('speak("Going forward")', 'speak("Aage ja raha hoon Sir")'),
    ('speak("Zoomed in")', 'speak("Zoom in kar diya Sir")'),
    ('speak("Zoomed out")', 'speak("Zoom out kar diya Sir")'),
    ('speak("Find opened")', 'speak("Find khol diya Sir")'),
    ('speak("New window opened")', 'speak("Naya window khol diya Sir")'),
    ('speak("Play pause toggled")', 'speak("Play pause kar diya Sir")'),
    ('speak("Next track")', 'speak("Next track Sir")'),
    ('speak("Previous track")', 'speak("Previous track Sir")'),
    ('speak("Media stopped")', 'speak("Media stop kar diya Sir")'),
    ('speak("Enter pressed")', 'speak("Enter kar diya Sir")'),
    ('speak("Escaped")', 'speak("Escape kar diya Sir")'),
    ('speak("Deleted")', 'speak("Delete kar diya Sir")'),
    ('speak("Backspace pressed")', 'speak("Backspace kar diya Sir")'),
    ('speak("Scrolled down")', 'speak("Neeche scroll kar diya Sir")'),
    ('speak("Scrolled up")', 'speak("Upar scroll kar diya Sir")'),
    ('speak("Left clicked")', 'speak("Click kar diya Sir")'),
    ('speak("Right clicked")', 'speak("Right click kar diya Sir")'),
    ('speak("Double clicked")', 'speak("Double click kar diya Sir")'),
    ('speak("Middle clicked")', 'speak("Middle click kar diya Sir")'),
    ('speak("Scrolled to top")', 'speak("Top pe scroll kar diya Sir")'),
    ('speak("Scrolled to bottom")', 'speak("Bottom pe scroll kar diya Sir")'),
    ('speak("Bold applied")', 'speak("Bold kar diya Sir")'),
    ('speak("Italic applied")', 'speak("Italic kar diya Sir")'),
    ('speak("Underline applied")', 'speak("Underline kar diya Sir")'),
    ('speak("Strikethrough applied")', 'speak("Strikethrough kar diya Sir")'),
    ('speak("Find and replace opened")', 'speak("Find and replace khol diya Sir")'),
    ('speak("Print dialog opened")', 'speak("Print dialog khol diya Sir")'),
    ('speak("Task manager opened")', 'speak("Task manager khol diya Sir")'),
    ('speak("Fullscreen toggled")', 'speak("Fullscreen kar diya Sir")'),
    ('speak("Closing app")', 'speak("App band kar raha hoon Sir")'),
    ('speak("New document")', 'speak("Naya document khol diya Sir")'),
    ('speak("Open file dialog")', 'speak("File open dialog khol diya Sir")'),
    ('speak("Rename mode")', 'speak("Rename mode Sir")'),
    ('speak("Tab restored")', 'speak("Tab restore kar diya Sir")'),
    ('speak("All tabs closed")', 'speak("Sab tabs band kar diye Sir")'),
    ('speak("Next tab")', 'speak("Next tab Sir")'),
    ('speak("Previous tab")', 'speak("Previous tab Sir")'),
    ('speak("History opened")', 'speak("History khol di Sir")'),
    ('speak("Bookmarks opened")', 'speak("Bookmarks khol diye Sir")'),
    ('speak("Downloads opened")', 'speak("Downloads khol diya Sir")'),
    ('speak("Developer tools opened")', 'speak("Developer tools khol diye Sir")'),
    ('speak("Incognito window opened")', 'speak("Incognito window khol diya Sir")'),
]

count = 0
for old, new in replacements:
    if old in content:
        content = content.replace(old, new)
        count += 1

open('engine/desktop_control.py', 'w', encoding='utf-8').write(content)
print(f'Done - {count} replacements made')
